parameters:
    amf_foursquare.service.class: AMF\FourSquareBundle\Service\FourSquare 

services:
    amf_foursquare.service:
        class: %amf_foursquare.service.class%
        scope: request
        arguments: [ "@request", %amf_foursquare.settings.client_id% , %amf_foursquare.settings.client_secret% ,  %amf_foursquare.settings.locale%, %amf_foursquare.settings.redirect_uri% , %amf_foursquare.settings.version% ]